name: Docker Image CI

on:
  push:
    branches: [test]
  pull_request:
    branches: [test]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@test
      - name: static
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWD: ${{ secrets.DOCKERHUB_PASSWD }}
        working-directory: ./
        run: docker build . -f Dockerfile.static
